project:

  type: website
  output-dir: docs

website:

  title: "Maxine Cruz"
  
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: TMCruz_CV.pdf
        icon: file-earmark-text
        text: CV
      - href: posts.qmd
        icon: easel
        text: Projects
      - href: pics.qmd
        icon: bug
        text: Bug Content & Whatnot
        
  sidebar: 
    - title: Bug Content & Whatnot
      style: docked
      contents: 
        - pics.qmd
        - travel.qmd
      
  page-footer: 
    background: $olive
    foreground: $blanched-almond
    left: "Copyright 2023, Maxine Cruz"
    right: 
      - href: https://quarto.org/
        text: "Made with Quarto"
      - href: https://github.com/mcx8/mcx8.github.io
        icon: github

format:

  html:
    theme:
      - styles.scss
    mainfont: "Zen Maru Gothic"
    page-layout: full

editor: visual

