project:

  type: website
  output-dir: docs

website:

  title: "Maxine Cruz"
  
  search: FALSE
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: TMCruz_CV.pdf
        icon: file-earmark-text
        text: CV
      - href: posts.qmd
        icon: easel
        text: Projects
      - href: https://mcx8.github.io/bug_n_stuff_website/pics.html
        icon: bug
        text: Bug Content & Whatnot
      
  page-footer: 
    background: $olive
    foreground: $blanched-almond
    left: "Copyright 2023, Maxine Cruz"
    right: 
      - href: https://quarto.org/
        text: "Made with Quarto"
      - href: https://github.com/mcx8/mcx8.github.io
        icon: github

format:

  html:
    theme:
      - styles.scss
    mainfont: "Zen Maru Gothic"
    page-layout: full

editor: visual

